<?php

declare(strict_types=1);

namespace LogTide\Tests\Unit\Breadcrumb;

use LogTide\Breadcrumb\Breadcrumb;
use LogTide\Enum\BreadcrumbType;
use LogTide\Enum\LogLevel;
use PHPUnit\Framework\TestCase;

final class BreadcrumbTest extends TestCase
{
    public function testCreation(): void
    {
        $b = new Breadcrumb(BreadcrumbType::HTTP, 'GET /api');

        $this->assertSame(BreadcrumbType::HTTP, $b->type);
        $this->assertSame('GET /api', $b->message);
        $this->assertNull($b->category);
        $this->assertNull($b->level);
        $this->assertEmpty($b->data);
        $this->assertGreaterThan(0, $b->timestamp);
    }

    public function testCreationWithAllFields(): void
    {
        $ts = microtime(true);
        $b = new Breadcrumb(
            BreadcrumbType::QUERY,
            'SELECT 1',
            category: 'db',
            level: LogLevel::DEBUG,
            data: ['duration_ms' => 1.5],
            timestamp: $ts,
        );

        $this->assertSame(BreadcrumbType::QUERY, $b->type);
        $this->assertSame('SELECT 1', $b->message);
        $this->assertSame('db', $b->category);
        $this->assertSame(LogLevel::DEBUG, $b->level);
        $this->assertSame(['duration_ms' => 1.5], $b->data);
        $this->assertSame($ts, $b->timestamp);
    }

    public function testToArrayMinimal(): void
    {
        $b = new Breadcrumb(BreadcrumbType::HTTP, 'GET /');
        $arr = $b->toArray();

        $this->assertSame('http', $arr['type']);
        $this->assertSame('GET /', $arr['message']);
        $this->assertArrayHasKey('timestamp', $arr);
        $this->assertArrayNotHasKey('category', $arr);
        $this->assertArrayNotHasKey('level', $arr);
        $this->assertArrayNotHasKey('data', $arr);
    }

    public function testToArrayFull(): void
    {
        $b = new Breadcrumb(
            BreadcrumbType::ERROR,
            'boom',
            category: 'exception',
            level: LogLevel::ERROR,
            data: ['code' => 42],
        );

        $arr = $b->toArray();

        $this->assertSame('error', $arr['type']);
        $this->assertSame('boom', $arr['message']);
        $this->assertSame('exception', $arr['category']);
        $this->assertSame('error', $arr['level']);
        $this->assertSame(['code' => 42], $arr['data']);
    }

    public function testTimestampAutoGenerated(): void
    {
        $before = microtime(true);
        $b = new Breadcrumb(BreadcrumbType::HTTP, 'test');
        $after = microtime(true);

        $this->assertGreaterThanOrEqual($before, $b->timestamp);
        $this->assertLessThanOrEqual($after, $b->timestamp);
    }
}
